version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: 
              ec2-52-48-65-240.eu-west-1.compute.amazonaws.com
            port: '5432'
            database: 
              d7bedrs2c6vect
            ssl: true
            user: 
              rmeaoobasltfhh
            password: 
              409c9ee24a03004ee873b1259519fcdf5f44461b837c7b9ffb99699676152213
            migrations: true
